################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../OLED/csrc/chinesetxt.c \
../OLED/csrc/mui.c \
../OLED/csrc/mui_u8g2.c \
../OLED/csrc/u8g2_arc.c \
../OLED/csrc/u8g2_bitmap.c \
../OLED/csrc/u8g2_box.c \
../OLED/csrc/u8g2_buffer.c \
../OLED/csrc/u8g2_button.c \
../OLED/csrc/u8g2_circle.c \
../OLED/csrc/u8g2_cleardisplay.c \
../OLED/csrc/u8g2_d_memory.c \
../OLED/csrc/u8g2_d_setup.c \
../OLED/csrc/u8g2_font.c \
../OLED/csrc/u8g2_fonts.c \
../OLED/csrc/u8g2_hvline.c \
../OLED/csrc/u8g2_input_value.c \
../OLED/csrc/u8g2_intersection.c \
../OLED/csrc/u8g2_kerning.c \
../OLED/csrc/u8g2_line.c \
../OLED/csrc/u8g2_ll_hvline.c \
../OLED/csrc/u8g2_message.c \
../OLED/csrc/u8g2_polygon.c \
../OLED/csrc/u8g2_selection_list.c \
../OLED/csrc/u8g2_setup.c \
../OLED/csrc/u8log.c \
../OLED/csrc/u8log_u8g2.c \
../OLED/csrc/u8log_u8x8.c \
../OLED/csrc/u8x8_8x8.c \
../OLED/csrc/u8x8_byte.c \
../OLED/csrc/u8x8_cad.c \
../OLED/csrc/u8x8_capture.c \
../OLED/csrc/u8x8_d_ssd1306_128x64_noname.c \
../OLED/csrc/u8x8_debounce.c \
../OLED/csrc/u8x8_display.c \
../OLED/csrc/u8x8_fonts.c \
../OLED/csrc/u8x8_gpio.c \
../OLED/csrc/u8x8_input_value.c \
../OLED/csrc/u8x8_message.c \
../OLED/csrc/u8x8_selection_list.c \
../OLED/csrc/u8x8_setup.c \
../OLED/csrc/u8x8_string.c \
../OLED/csrc/u8x8_u16toa.c \
../OLED/csrc/u8x8_u8toa.c 

C_DEPS += \
./OLED/csrc/chinesetxt.d \
./OLED/csrc/mui.d \
./OLED/csrc/mui_u8g2.d \
./OLED/csrc/u8g2_arc.d \
./OLED/csrc/u8g2_bitmap.d \
./OLED/csrc/u8g2_box.d \
./OLED/csrc/u8g2_buffer.d \
./OLED/csrc/u8g2_button.d \
./OLED/csrc/u8g2_circle.d \
./OLED/csrc/u8g2_cleardisplay.d \
./OLED/csrc/u8g2_d_memory.d \
./OLED/csrc/u8g2_d_setup.d \
./OLED/csrc/u8g2_font.d \
./OLED/csrc/u8g2_fonts.d \
./OLED/csrc/u8g2_hvline.d \
./OLED/csrc/u8g2_input_value.d \
./OLED/csrc/u8g2_intersection.d \
./OLED/csrc/u8g2_kerning.d \
./OLED/csrc/u8g2_line.d \
./OLED/csrc/u8g2_ll_hvline.d \
./OLED/csrc/u8g2_message.d \
./OLED/csrc/u8g2_polygon.d \
./OLED/csrc/u8g2_selection_list.d \
./OLED/csrc/u8g2_setup.d \
./OLED/csrc/u8log.d \
./OLED/csrc/u8log_u8g2.d \
./OLED/csrc/u8log_u8x8.d \
./OLED/csrc/u8x8_8x8.d \
./OLED/csrc/u8x8_byte.d \
./OLED/csrc/u8x8_cad.d \
./OLED/csrc/u8x8_capture.d \
./OLED/csrc/u8x8_d_ssd1306_128x64_noname.d \
./OLED/csrc/u8x8_debounce.d \
./OLED/csrc/u8x8_display.d \
./OLED/csrc/u8x8_fonts.d \
./OLED/csrc/u8x8_gpio.d \
./OLED/csrc/u8x8_input_value.d \
./OLED/csrc/u8x8_message.d \
./OLED/csrc/u8x8_selection_list.d \
./OLED/csrc/u8x8_setup.d \
./OLED/csrc/u8x8_string.d \
./OLED/csrc/u8x8_u16toa.d \
./OLED/csrc/u8x8_u8toa.d 

OBJS += \
./OLED/csrc/chinesetxt.o \
./OLED/csrc/mui.o \
./OLED/csrc/mui_u8g2.o \
./OLED/csrc/u8g2_arc.o \
./OLED/csrc/u8g2_bitmap.o \
./OLED/csrc/u8g2_box.o \
./OLED/csrc/u8g2_buffer.o \
./OLED/csrc/u8g2_button.o \
./OLED/csrc/u8g2_circle.o \
./OLED/csrc/u8g2_cleardisplay.o \
./OLED/csrc/u8g2_d_memory.o \
./OLED/csrc/u8g2_d_setup.o \
./OLED/csrc/u8g2_font.o \
./OLED/csrc/u8g2_fonts.o \
./OLED/csrc/u8g2_hvline.o \
./OLED/csrc/u8g2_input_value.o \
./OLED/csrc/u8g2_intersection.o \
./OLED/csrc/u8g2_kerning.o \
./OLED/csrc/u8g2_line.o \
./OLED/csrc/u8g2_ll_hvline.o \
./OLED/csrc/u8g2_message.o \
./OLED/csrc/u8g2_polygon.o \
./OLED/csrc/u8g2_selection_list.o \
./OLED/csrc/u8g2_setup.o \
./OLED/csrc/u8log.o \
./OLED/csrc/u8log_u8g2.o \
./OLED/csrc/u8log_u8x8.o \
./OLED/csrc/u8x8_8x8.o \
./OLED/csrc/u8x8_byte.o \
./OLED/csrc/u8x8_cad.o \
./OLED/csrc/u8x8_capture.o \
./OLED/csrc/u8x8_d_ssd1306_128x64_noname.o \
./OLED/csrc/u8x8_debounce.o \
./OLED/csrc/u8x8_display.o \
./OLED/csrc/u8x8_fonts.o \
./OLED/csrc/u8x8_gpio.o \
./OLED/csrc/u8x8_input_value.o \
./OLED/csrc/u8x8_message.o \
./OLED/csrc/u8x8_selection_list.o \
./OLED/csrc/u8x8_setup.o \
./OLED/csrc/u8x8_string.o \
./OLED/csrc/u8x8_u16toa.o \
./OLED/csrc/u8x8_u8toa.o 

OBJS__QUOTED += \
"OLED\csrc\chinesetxt.o" \
"OLED\csrc\mui.o" \
"OLED\csrc\mui_u8g2.o" \
"OLED\csrc\u8g2_arc.o" \
"OLED\csrc\u8g2_bitmap.o" \
"OLED\csrc\u8g2_box.o" \
"OLED\csrc\u8g2_buffer.o" \
"OLED\csrc\u8g2_button.o" \
"OLED\csrc\u8g2_circle.o" \
"OLED\csrc\u8g2_cleardisplay.o" \
"OLED\csrc\u8g2_d_memory.o" \
"OLED\csrc\u8g2_d_setup.o" \
"OLED\csrc\u8g2_font.o" \
"OLED\csrc\u8g2_fonts.o" \
"OLED\csrc\u8g2_hvline.o" \
"OLED\csrc\u8g2_input_value.o" \
"OLED\csrc\u8g2_intersection.o" \
"OLED\csrc\u8g2_kerning.o" \
"OLED\csrc\u8g2_line.o" \
"OLED\csrc\u8g2_ll_hvline.o" \
"OLED\csrc\u8g2_message.o" \
"OLED\csrc\u8g2_polygon.o" \
"OLED\csrc\u8g2_selection_list.o" \
"OLED\csrc\u8g2_setup.o" \
"OLED\csrc\u8log.o" \
"OLED\csrc\u8log_u8g2.o" \
"OLED\csrc\u8log_u8x8.o" \
"OLED\csrc\u8x8_8x8.o" \
"OLED\csrc\u8x8_byte.o" \
"OLED\csrc\u8x8_cad.o" \
"OLED\csrc\u8x8_capture.o" \
"OLED\csrc\u8x8_d_ssd1306_128x64_noname.o" \
"OLED\csrc\u8x8_debounce.o" \
"OLED\csrc\u8x8_display.o" \
"OLED\csrc\u8x8_fonts.o" \
"OLED\csrc\u8x8_gpio.o" \
"OLED\csrc\u8x8_input_value.o" \
"OLED\csrc\u8x8_message.o" \
"OLED\csrc\u8x8_selection_list.o" \
"OLED\csrc\u8x8_setup.o" \
"OLED\csrc\u8x8_string.o" \
"OLED\csrc\u8x8_u16toa.o" \
"OLED\csrc\u8x8_u8toa.o" 

C_DEPS__QUOTED += \
"OLED\csrc\chinesetxt.d" \
"OLED\csrc\mui.d" \
"OLED\csrc\mui_u8g2.d" \
"OLED\csrc\u8g2_arc.d" \
"OLED\csrc\u8g2_bitmap.d" \
"OLED\csrc\u8g2_box.d" \
"OLED\csrc\u8g2_buffer.d" \
"OLED\csrc\u8g2_button.d" \
"OLED\csrc\u8g2_circle.d" \
"OLED\csrc\u8g2_cleardisplay.d" \
"OLED\csrc\u8g2_d_memory.d" \
"OLED\csrc\u8g2_d_setup.d" \
"OLED\csrc\u8g2_font.d" \
"OLED\csrc\u8g2_fonts.d" \
"OLED\csrc\u8g2_hvline.d" \
"OLED\csrc\u8g2_input_value.d" \
"OLED\csrc\u8g2_intersection.d" \
"OLED\csrc\u8g2_kerning.d" \
"OLED\csrc\u8g2_line.d" \
"OLED\csrc\u8g2_ll_hvline.d" \
"OLED\csrc\u8g2_message.d" \
"OLED\csrc\u8g2_polygon.d" \
"OLED\csrc\u8g2_selection_list.d" \
"OLED\csrc\u8g2_setup.d" \
"OLED\csrc\u8log.d" \
"OLED\csrc\u8log_u8g2.d" \
"OLED\csrc\u8log_u8x8.d" \
"OLED\csrc\u8x8_8x8.d" \
"OLED\csrc\u8x8_byte.d" \
"OLED\csrc\u8x8_cad.d" \
"OLED\csrc\u8x8_capture.d" \
"OLED\csrc\u8x8_d_ssd1306_128x64_noname.d" \
"OLED\csrc\u8x8_debounce.d" \
"OLED\csrc\u8x8_display.d" \
"OLED\csrc\u8x8_fonts.d" \
"OLED\csrc\u8x8_gpio.d" \
"OLED\csrc\u8x8_input_value.d" \
"OLED\csrc\u8x8_message.d" \
"OLED\csrc\u8x8_selection_list.d" \
"OLED\csrc\u8x8_setup.d" \
"OLED\csrc\u8x8_string.d" \
"OLED\csrc\u8x8_u16toa.d" \
"OLED\csrc\u8x8_u8toa.d" 

C_SRCS__QUOTED += \
"../OLED/csrc/chinesetxt.c" \
"../OLED/csrc/mui.c" \
"../OLED/csrc/mui_u8g2.c" \
"../OLED/csrc/u8g2_arc.c" \
"../OLED/csrc/u8g2_bitmap.c" \
"../OLED/csrc/u8g2_box.c" \
"../OLED/csrc/u8g2_buffer.c" \
"../OLED/csrc/u8g2_button.c" \
"../OLED/csrc/u8g2_circle.c" \
"../OLED/csrc/u8g2_cleardisplay.c" \
"../OLED/csrc/u8g2_d_memory.c" \
"../OLED/csrc/u8g2_d_setup.c" \
"../OLED/csrc/u8g2_font.c" \
"../OLED/csrc/u8g2_fonts.c" \
"../OLED/csrc/u8g2_hvline.c" \
"../OLED/csrc/u8g2_input_value.c" \
"../OLED/csrc/u8g2_intersection.c" \
"../OLED/csrc/u8g2_kerning.c" \
"../OLED/csrc/u8g2_line.c" \
"../OLED/csrc/u8g2_ll_hvline.c" \
"../OLED/csrc/u8g2_message.c" \
"../OLED/csrc/u8g2_polygon.c" \
"../OLED/csrc/u8g2_selection_list.c" \
"../OLED/csrc/u8g2_setup.c" \
"../OLED/csrc/u8log.c" \
"../OLED/csrc/u8log_u8g2.c" \
"../OLED/csrc/u8log_u8x8.c" \
"../OLED/csrc/u8x8_8x8.c" \
"../OLED/csrc/u8x8_byte.c" \
"../OLED/csrc/u8x8_cad.c" \
"../OLED/csrc/u8x8_capture.c" \
"../OLED/csrc/u8x8_d_ssd1306_128x64_noname.c" \
"../OLED/csrc/u8x8_debounce.c" \
"../OLED/csrc/u8x8_display.c" \
"../OLED/csrc/u8x8_fonts.c" \
"../OLED/csrc/u8x8_gpio.c" \
"../OLED/csrc/u8x8_input_value.c" \
"../OLED/csrc/u8x8_message.c" \
"../OLED/csrc/u8x8_selection_list.c" \
"../OLED/csrc/u8x8_setup.c" \
"../OLED/csrc/u8x8_string.c" \
"../OLED/csrc/u8x8_u16toa.c" \
"../OLED/csrc/u8x8_u8toa.c" 


